[tool.poetry]
name = ".dotfiles"
version = "0.1.0"
description = ""
authors = ["Larry Smith Jr. <mrlesmithjr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ansible-base = "2.10.5"
ansible = "2.10.7"
arrow = "0.17.0"
binaryornot = "0.4.4"
certifi = "2020.12.5"
cffi = "1.14.5"
chardet = "4.0.0"
click = "7.1.2"
cookiecutter = "1.7.2"
cryptography = "3.4.5"
future = "0.18.2"
Glances = "3.1.6.2"
idna = "2.10"
jinja2-time = "0.2.0"
Jinja2 = "2.11.3"
MarkupSafe = "1.1.1"
ntlm-auth = "1.5.0"
packaging = "20.9"
pip-tools = "5.5.0"
poyo = "0.5.0"
psutil = "5.8.0"
pycparser = "2.20"
pyparsing = "2.4.7"
python-dateutil = "2.8.1"
python-slugify = "4.0.1"
pywinrm = "0.4.1"
PyYAML = "5.4.1"
requests_ntlm = "1.1.0"
requests = "2.25.1"
six = "1.15.0"
text-unidecode = "1.3"
urllib3 = "1.26.3"
xmltodict = "0.12.0"

[tool.poetry.dev-dependencies]
ansible-lint = "5.0.0"
appdirs = "1.4.4"
astroid = "2.4.2"
autopep8 = "1.5.5"
bracex = "2.1.1"
click = "7.1.2"
colorama = "0.4.4"
commonmark = "0.9.1"
distlib = "0.3.1"
enrich = "1.2.6"
filelock = "3.0.12"
flake8 = "3.8.4"
future = "0.18.2"
isort = "5.7.0"
Jinja2 = "2.11.3"
joblib = "1.0.1"
lazy-object-proxy = "1.4.3"
livereload = "2.6.3"
lunr = {version = "0.5.8", extras = ["languages"]}
Markdown = "3.3.3"
MarkupSafe = "1.1.1"
mccabe = "0.6.1"
mkdocs = "1.1.2"
nltk = "3.5"
packaging = "20.9"
pluggy = "0.13.1"
py = "1.10.0"
pycodestyle = "2.6.0"
pyflakes = "2.2.0"
Pygments = "2.8.0"
pylint = "2.6.2"
pyparsing = "2.4.7"
PyYAML = "5.4.1"
regex = "2020.11.13"
rich = "9.11.0"
"ruamel.yaml" = "0.16.12"
six = "1.15.0"
toml = "0.10.2"
tornado = "6.1"
tox = "3.22.0"
tqdm = "4.56.2"
typing-extensions = "3.7.4.3"
virtualenv = "20.4.2"
wcmatch = "8.1.1"
wrapt = "1.12.1"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
