---
brew_cask_packages:
  - atom
  - docker
  - dropbox
  - firefox
  - gimp
  - google-backup-and-sync
  - google-chrome
  #  - google-drive
  - google-hangouts
  # - google-photos-backup-and-sync
  - iterm2
  - keepassx
  - kodi
  - lastpass
  # - libreoffice
  # - macvim
  - meld
  - pandora
  - powershell
  # - royal-tsx
  - skype
  - slack
  # - sling
  - spotify
    # - sublime-text
  - tigervnc-viewer
  - unetbootin
  - vagrant
  - vagrant-manager
  - virtualbox
  - virtualbox-extension-pack
    # - visual-studio-code
  # - vmware-fusion
  - vnc-viewer
brew_packages:
  - apm-bash-completion
  - autoconf
  - bash-completion
  - bash-git-prompt
  # - boot2docker
  - consul
  - docker-completion
    # - docker-compose
  - docker-compose-completion
    # - docker-machine
  - doxygen
  - flint-checker
  - gdbm
  - git
  - git-lfs
  - go
  - jq
  - nmap
  - npm
  - nomad
  - openssl
  - packer
  - packer-completion
  - pip-completion
    # - pyenv
  - python
  - rancher-compose
    # - rbenv
  - readline
    # - ruby-build
  - shellcheck
  - ssh-copy-id
  - terraform
  - terraform-inventory
  - terraform-provisioner-ansible
  - tmux
  - tree
  - vagrant-completion
  - vault
  - vim
  - wget
    # - zsh
    # - zsh-syntax-highlighting
install_homebrew_if_missing: true
upgrade_homebrew_packages: false
