---
python_modules:
  - name: ara
    state: present
  - name: autopep8
    state: present
  - name: beautysh
    state: present
  - name: docker
    state: present
  - name: django
    state: absent
  - name: doc8
    state: present
  - name: flask
    state: present
  - name: GitPython
    state: present
  - name: ipaddr
    state: present
  - name: jmespath
    state: present
  - name: keyring
    state: present
  - name: molecule
    state: present
  - name: netaddr
    state: present
  - name: nmap
    state: absent
  - name: passlib
    state: absent
  - name: pep8
    state: present
  - name: pipreqs
    state: present
  - name: pygithub
    state: present
  - name: pylama
    state: present
  - name: pylint
    state: present
  - name: pymongo
    state: absent
  - name: pyOpenSSL
    state: present
  - name: python-consul
    state: absent
  - name: python-language-server[all]
    state: present
  - name: python-vagrant
    state: absent
  # pyvim breaks locating pyvmomi using Ansible
  # https://github.com/ansible/ansible/issues/44245
  - name: pyvim
    state: absent
  - name: pyvmomi
    state: present
  - name: pywinrm
    state: present
  - name: requests
    state: present
  - name: sphinx
    state: present
  - name: TerraformToAnsibleInventory
    state: absent
  - name: testinfra
    state: present
  - name: tox
    state: present
